server:
  port: "${port:8080}"

management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true

spring:
  security:
    oauth2:
      client:
        registration:
          strava:
            provider: strava-provider
            client-id: 58845
            client-secret: 17d785489dab9c4242d13aa0711fcbcb5edca6a0
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://neois.online:8080/login/oauth2/code/
            scope:
              - activity:read,profile:read_all
        provider:
          strava-provider:
            tokenUri: https://www.strava.com/api/v3/oauth/token
            authorizationUri: https://www.strava.com/api/v3/oauth/authorize?response_type=code
            user-info-uri: https://www.strava.com/api/v3/athlete
            user-name-attribute: id
  data:
    mongodb:
      username = doadmin
      password = m7Ja5rI13O2Ej908
      host = mongodb+srv://private-db-mongodb-blr1-55579-c14ecfc5.mongo.ondigitalocean.com
      database = admin
